// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgf8psP-yxQsXRb1VvqCCsiG9yHGhSxno',
    appId: '1:823590010110:web:a7afc3925f8acb908979af',
    messagingSenderId: '823590010110',
    projectId: 'matrix-edge-demo-website',
    authDomain: 'matrix-edge-demo-website.firebaseapp.com',
    storageBucket: 'matrix-edge-demo-website.firebasestorage.app',
    measurementId: 'G-LRJV03EH0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbW29v-3pgeN3FiAbfeMDBbbyIT532MK8',
    appId: '1:823590010110:android:82851a32a9c927988979af',
    messagingSenderId: '823590010110',
    projectId: 'matrix-edge-demo-website',
    storageBucket: 'matrix-edge-demo-website.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjsUsfdWMIF1rr4EYl_v__1B8NH_jjsEM',
    appId: '1:823590010110:ios:dc4032acb06925208979af',
    messagingSenderId: '823590010110',
    projectId: 'matrix-edge-demo-website',
    storageBucket: 'matrix-edge-demo-website.firebasestorage.app',
    iosBundleId: 'com.example.website',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjsUsfdWMIF1rr4EYl_v__1B8NH_jjsEM',
    appId: '1:823590010110:ios:dc4032acb06925208979af',
    messagingSenderId: '823590010110',
    projectId: 'matrix-edge-demo-website',
    storageBucket: 'matrix-edge-demo-website.firebasestorage.app',
    iosBundleId: 'com.example.website',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgf8psP-yxQsXRb1VvqCCsiG9yHGhSxno',
    appId: '1:823590010110:web:12d97d0ab23d1e548979af',
    messagingSenderId: '823590010110',
    projectId: 'matrix-edge-demo-website',
    authDomain: 'matrix-edge-demo-website.firebaseapp.com',
    storageBucket: 'matrix-edge-demo-website.firebasestorage.app',
    measurementId: 'G-JJGJ3Y59NN',
  );
}
